<a href="https://colab.research.google.com/github/HyungjunAn/ml/blob/main/Beginning_of_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Beginning of TesorFlow

In [ ]:
import tensorflow as tf

print(tf.__version__)

node1 = tf.constant(3.0)
node2 = tf.constant(4.0)

node3 = node1 + node2

print(node1)

tf.print(node1)
tf.print(node3)

def myAdd(a, b):
  return a + b

#ph_node3 = ph_node1 + ph_node2

myAdd(tf.constant([1.0, 2.0]), tf.constant([2.5, 3.0]))
tf.print(myAdd(tf.constant([1, 2]), tf.constant([2, 3])))

2.4.1
tf.Tensor(3.0, shape=(), dtype=float32)
3
7
[3 5]


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.5, 5. ], dtype=float32)>

# Linear Regression

## Single_Variable

Tensroflow

In [ ]:
import numpy as np
import tensorflow as tf

x_train = [1, 2, 3, 4]
y_train = [0, -1, -2, -3]

tf.model = tf.keras.Sequential()
# units == output shape, input_dim == input shape
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=1, name = 'layer_1'))

sgd = tf.keras.optimizers.SGD(lr=0.1)  # SGD == standard gradient descendent, lr == learning rate
tf.model.compile(loss='mse', optimizer=sgd)  # mse == mean_squared_error, 1/m * sig (y'-y)^2

# prints summary of the model to the terminal
tf.model.summary()

# fit() executes training
history = tf.model.fit(x_train, y_train, epochs=200, verbose = 0)

print(history.history['loss'])

# predict() returns predicted value
y_predict = tf.model.predict(np.array([5, 4]))
print(y_predict)

### Keras

In [ ]:
import numpy as np
import tensorflow as tf

x_train = [1, 2, 3, 4]
y_train = [0, -1, -2, -3]

tf.model = tf.keras.Sequential()
# units == output shape, input_dim == input shape
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=1, name = 'layer_1'))

sgd = tf.keras.optimizers.SGD(lr=0.1)  # SGD == standard gradient descendent, lr == learning rate
tf.model.compile(loss='mse', optimizer=sgd)  # mse == mean_squared_error, 1/m * sig (y'-y)^2

# prints summary of the model to the terminal
tf.model.summary()

# fit() executes training
history = tf.model.fit(x_train, y_train, epochs=200, verbose = 0)

print(history.history['loss'])

# predict() returns predicted value
y_predict = tf.model.predict(np.array([5, 4]))
print(y_predict)

Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer_1 (Dense)              (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
[11.362650871276855, 5.255949974060059, 2.50504994392395, 1.261380672454834, 0.69493567943573, 0.4330272078514099, 0.3082974851131439, 0.24557945132255554, 0.2110998034477234, 0.18967141211032867, 0.17445358633995056, 0.16235429048538208, 0.15196582674980164, 0.14263783395290375, 0.1340610384941101, 0.12608033418655396, 0.11861089617013931, 0.11160019040107727, 0.10501114279031754, 0.098814457654953, 0.09298485517501831, 0.08749984204769135, 0.08233868330717087, 0.07748208940029144, 0.07291201502084732, 0.0686115026473999, 0.06456466764211655, 0.06075651943683624, 0.05717301741242409, 0.05380084365606308, 0.05062756687402725, 0.04764148592948913

## Multi-Variable

### Tensorflow

In [ ]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

'''
0 Cost:  7105.46
Prediction:
 [[ 80.82241058]
 [ 92.26364136]
 [ 93.70250702]
 [ 98.09217834]
 [ 72.51759338]]
10 Cost:  5.89726
Prediction:
 [[ 155.35159302]
 [ 181.85691833]
 [ 181.97254944]
 [ 194.21760559]
 [ 140.85707092]]
...
1990 Cost:  3.18588
Prediction:
 [[ 154.36352539]
 [ 182.94833374]
 [ 181.85189819]
 [ 194.35585022]
 [ 142.03240967]]
2000 Cost:  3.1781
Prediction:
 [[ 154.35881042]
 [ 182.95147705]
 [ 181.85035706]
 [ 194.35533142]
 [ 142.036026  ]]
'''

AttributeError: ignored

### Keras

In [ ]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

tf.model = tf.keras.Sequential()

tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3))  # input_dim=3 gives multi-variable regression
tf.model.add(tf.keras.layers.Activation('linear'))  # this line can be omitted, as linear activation is default
# advanced reading https://towardsdatascience.com/activation-functions-neural-networks-1cbd9f8d91d6

tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
tf.model.summary()
history = tf.model.fit(x_data, y_data, epochs=100)

y_predict = tf.model.predict(np.array([[72., 93., 90.]]))
print(y_predict)

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 1)                 4         
_________________________________________________________________
activation (Activation)      (None, 1)                 0         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1/1 [==============================] - 0s 223ms/step - loss: 23593.3320
Epoch 2/100
1/1 [==============================] - 0s 3ms/step - loss: 7397.0234
Epoch 3/100
1/1 [==============================] - 0s 4ms/step - loss: 2320.3406
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 729.0699
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 230.2907
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 73.9496
Epoch 7/100
1/1 [====================